export const ALPHABETS = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
export const NUMBERS = "0123456789";

export const COMPONENTS = [
  "VAccordion",
  "VAccordionHeader",
  "VAccordionItem",
  "VAccordionPanel",
  "VAccordionTrigger",
  "VButton",
  "VCheckbox",
  "VCheckboxGroup",
  "VCheckboxGroupDescription",
  "VCheckboxGroupError",
  "VCheckboxGroupTitle",
  "VContent",
  "VContentDescription",
  "VContentTitle",
  "VDialog",
  "VDialogDescription",
  "VDialogTitle",
  "VDropdown",
  "VDropdownItem",
  "VDropdownMenu",
  "VDropdownTrigger",
  "VField",
  "VFieldDescription",
  "VFieldError",
  "VFieldLabel",
  "VFieldset",
  "VFieldsetDescription",
  "VFieldsetTitle",
  "VForm",
  "VFormDescription",
  "VFormTitle",
  "VNumberInput",
  "VPopover",
  "VPopoverContent",
  "VPopoverTrigger",
  "VProgress",
  "VRadio",
  "VRadioGroup",
  "VRadioGroupDescription",
  "VRadioGroupTitle",
  "VRovingTabindex",
  "VRovingTabindexItem",
  "VTabs",
  "VTabsList",
  "VTabsPanel",
  "VTabsTrigger",
  "VTextInput",
  "VTooltip",
  "VTooltipContent",
  "VTooltipTrigger",
  "VTransition",
] as const;
