// Generated by build-constants.js

export const RULES = [
  "after",
  "before",
  "float",
  "integer",
  "isEmail",
  "isEqual",
  "max",
  "maxLength",
  "maxSize",
  "min",
  "minLength",
  "minSize",
  "pattern",
  "required",
] as const;
